# Потойбічні істоти
creatures:
  # Мінімальна горизонтальна відстань (у блоках) від точки спавну світу, на якій починають
  # з'являтися міфічні істоти (природний спавн + спавн у структурах). /creature spawn ігнорує це.
  min-spawn-distance: 2000
