name: Mysteries-Above
version: 0.0
main: me.vangoo.LotmPlugin
api-version: "1.21"

commands:
  beyonder:
    description: Manage your Beyonder abilities and pathways
    usage: /<command> [args]
  mastery:
    description: manage mastery
    usage: /mastery [get|set|add] [значення]