name: Mysteries-Above
version: 0.0
main: me.vangoo.MysteriesAbovePlugin
api-version: "1.21"

commands:
  pathway:
    description: Manage your Beyonder abilities and pathways
    usage: /<command> <get|set|remove> ...
  mastery:
    description: Manage mastery
    usage: /mastery [info]
  rampager:
    description: оудап
    usage: /rampager set <1-100>